var artikelNamn = ["Körsbärstomater Kvist",
"Tomater Skivade 1kg",
"Cherrytomater Röda",
"Körsbärstomat lösvikt",
"Cherrytomater Gula",
"Tomater Biff",
"Vitlök Fläta 500g",
"Wokmix Bas 5kg",
"Rotsaksgratäng 2kg",
"Proviva Fruktdryck Mango 1.75L",
"Smoothie Blackberry/Strawberry/Blackcurrant 750ml",
"Delicatoboll Mini 18g",
"Kanelbullar St",
"Dammsugare Mini 18g",
"Lussekatt 55g",
"Muffins Saffran 4x30g",
"Kärleksmumstårta 850g",
"Basilika Lösvikt ",
"Vetelängd 300g",
"Dill ",
"Gräslök Lösvikt            Ewe",
"Mynta Ask Krav",
"Timjan Krav 50g Ask",
"Bacon Skivat Rulle",
"Nötfärs 15-17% Eko 2.5kg",
"Nötfärs 15% Eko Trp 4x2.5kg",
"Fransyska Strimlad 1x1x4",
"Högrev Tä Se 2x2x2 2.5/10kg",
"Falukorv Hel Rak 23%",
"Falukorv Skivad 17% ",
"Falukorv Skivad 23%",
"Hamburgerkött Skivad",
"Parisare Skivad 60g",
"Cognacsmedwurst 300g/3kg",
"Tjälknöl S-v ",
"Norrlandsprinskorv",
"Westervikskorv 650g",
"Salami 300g",
"Julskinka Kokt 2kg",
"Julskinka Kokt ca3.5kg",
"Julskinka Kokt Skivad ca1kg",
"Julskinka Kokt Skivad 500g",
"Julskinka Kokt Msv 3.5-5kg",
"Norrlandskinka Rökt Skivad 1kg",
"Snickarskinka Kallrökt Skivad",
"Skinka Alspånsrökt Skivad 500g",
"Skinka Rökt Skivad 500g",
"Skinka Flatrökt 3kg",
"Kokkorv 55 g",
"Renkorv Rökt  300g/3kg",
"Limpa 700g",
"Malmbergslimpa Skivad 500g",
"Joggalimpa Skivad 650g",
"Tyrolerlimpa 700g",
"Potatislimpa Skivad 500g",
"Norrgott Ns 75% 600g",
"Norrgott Xs 75% 600g",
"Norrgott Ns 75% 300g",
"Creme Fraiche Laktosfri 34% 3kg",
"Creme Fraiche Laktosfri 34% 200g",
"Créme Fraiche",
"Filmjölk Krav 3% 1kg",
"Fjällfil Naturell 4.2% 1kg",
"A-fil Krav 3% 1L",
"Skogsbärsfil 2.7%",
"Jordgubbsfil 2.7%",
"Päronfil 2.5%",
"Hallonfil M Vanilj 2.7%",
"Långfil 3%1L",
"Lättmjölk 0.5% Krav 20L",
"Lättmjölk 0.5% Krav 1L",
"Lättmjölk Krav 10L",
"Mellanmjölk Krav 1.5% 1L",
"Mellanmjölk Krav 20L",
"Mellanmjölk Krav 10L",
"Standardmjölk Krav 3% 1L",
"Vispgrädde Krav 40% 1L",
"Yoghurt Mild Naturell 3% 1kg",
"A-yoghurt Mild 4.4% 1kg",
"Fruktyoghurt Jordgubb/Smultron 2.5% 1kg",
"Fruktyoghurt Jordgubb/Smultron 1%1kg",
"Fruktyoghurt 1% Blåbär/hallon",
"Fjällyoghurt 3.6% Blåbär/Smultron",
"Fjällyoghurt Hallon 3.6%",
"Fruktyoghurt Hjortron/Äpple 2.5% 1kg",
"Fruktyoghurt 2.5% Jordgubb/Smultron",
"Fruktyoghurt Blåbär 2.5% 1kg",
"Fruktyoghurt Jordgubb 1% 1kg",
"Fruktyoghurt Hallon 1% 1kg",
"Fruktyoghurt Blåbär/Hallon 1% 1kg",
"Vaniljyoghurt 2.6% 1kg",
"Yoghurt Mild Vanilj 2.7%",
"Hälsoyoghurt Laktosfri Jordgubb 1L",
"Hälsoyoghurt Laktosfri Blåbär/vanilj 1000g",
"Hälsoyoghurt Hallon Laktosfri 0.5% 1L ",
"Fjällyoghurt Blåbär 3.6% 1kg",
"Comté St Antoine",
"Grana Padano Strimlad 1kg",
"Brillat Savarin Affine 500g",
"Danablu Ädel",
"Matpotatis Tvättad 38-50mm 10kg",
"Potatis Tvättad ",
"Potatis Skalad 7kg",
"Potatis Rå Strimlad 7kg",
"Minut Matpotatis 3kg",
"Kulpotatis Förkokt",
"Potatis Rund Förkokt",
"Pitepalt utan fläsk 20p",
"Pitepalt med fläsk 20p 2.80kg",
"Ägg Lv M Inbur 30p",
"Ägg 18-pack Medium 1071g",
"Ägg M Krav Krt 12-p 714g",
"Ägg 15p",
"Ägg 18-p 1071g",
"Ägg 12-p Large",
"Bakpulver 2.5kg",
"Strössel Saltlakrits Flakes 1kg",
"Ärter Gula Torra 10kg",
"Ris Grönsaker & Kyckling 6m Eko 190g",
"Spaghetti Tomat & Mozzarella 8m Eko 190g",
"Päronpuré 4m Eko 190g",
"Päronkräm Osockrad Kallrörd",
"Salsa Medium Chunky 2.1kg",
"Thai Sweet Chilisås 5.5kg/4.7L",
"Sunt & Gott Naturell",
"Plommon Kärnfria 200g",
"Ananas Skivad Lätt Sockerlag 836g",
"Ananas krossad i juice",
"Päronhalvor Juice 810g",
"Mjukglassmix Gräddglass 2L",
"Syrup Gammeldags Vanilj 1L",
"Hirsflingor 250g",
"Bönor Gröna Hela 800g",
"Champinjon Skivad 800g",
"Oliver Svarta Uk 350g",
"Kronärtskockshjärtan Kvartar 1.7kg",
"Skorpor Graham/Kardemumma 160g",
"Smörgåsrån Fullkorn 155g",
"Skorpor 400g",
"Måltidsdricka Citron Light 1+5 5L",
"Måltidsdricka Blodapelsin 5L",
"Gainomax Blåbär",
"Lättdryck Sv Vinbär",
"Krögarns Mellanrost 100g",
"Löfbergs Fair Kok Mellan Eko/FT 500g",
"Gevalia Prof. Maskinbrygg Mellanrost 100g",
"Gevalia Prof. Instant Mellanrost RA 250g",
"Hallongrotta 42g 50st",
"Cookies Havre GF",
"Cookies Äpple & Kanel GF",
"Citronkaka 800g",
"Drömmix 3 Sorter 600g",
"Mandelhjärta Salt 20-p",
"Maränger 120g",
"Pepparkakshjärta Stora med hål",
"Fruktsoda Fl 33cl",
"Jordgubbssoda 33cl",
"Sockerdricka 33cl Fl",
"Portello 33cl Pet",
"Aqua Lapplandia Källvatten 250ml",
"Åive Stilla Vatten 50cl Pet",
"Åive Stilla Vatten 33cl Pet",
"Åive Kallkällevatten 50cl",
"Neapolitans Dark/orange 5g",
"Trossar melon 60st",
"Delikatesspraliner 750g",
"Fruktkola Lv Insl Påse 1kg",
"Lakritsbåtar Lv  2.4kg",
"Blandat & Klart",
"Julmix Skumtomtar Gsd",
"Koriander Malen 800g",
"Fem Peppar",
"Svartpeppar Portion 2000st  Imp",
"Matolja 5L",
"Majsolja 3L",
"Rapsolja Bib 10L",
"Mellanmjölk Lång Hållbarhet 1.5% 1L",
"Chokladmjölk 1.5% 1L",
"Vispgrädde Laktosfri 38% 2.5dl",
"Solhavremjölk 1L",
"Rigatoni 200g",
"Redning Kall 6kg",
"Havssalt Grovt 20kg",
"Hasselnötter med skal 300g",
"Solroskärna Rostad Saltad 200g",
"Bitsocker Mini 500g",
"Canderel Box 250st",
"Canderel Strö Refill",
"Apelsinmarmelad Ex fin 28g",
"Lingonsylt 620g",
"Björnbärssylt",
"Bearnaisesås 1L/973g",
"Pizzasås 2.95kg",
"Te Mango & Jordgubb Svart 100p",
"Te Skogsbär Utz 20p 2g",
"Ruby Red Berries Rooibos FT 16p",
"Äppelcidervinäger Honung 750ml",
"Wokbägare Vit 750ml 50st",
"Dressingbägare 6cl 250st",
"Hämtbox Vit 2fack Hp4",
"Plastfilm Dispenser 30cm 300m",
"Livsmedelsfilm med dispenser 45cm 300m",
"Torkmedel Indus Bomb",
"Torkmedel Indus 10L",
"Korvpapper 11x14cm 4000st",
"Gaffel Ex Svart 180mm 100st",
"Gaffel Finbestick",
"Kniv Viking 190mm 100st",
"Kaffesked 115mm Vit",
"Sugrör Raka Bl 20cm 1000st",
"Kaffekopp med öra Brun/vit 18cl 50st",
"Bägare 60ml",
"Svinto Tvålull 200g",
"Dunicel Dukrulle Soft Violet 1st",
"Rent Handdisk 1L",
"Vinylhandske Trp Opudrad M 100st",
"Vinylhandske M Puderfri",
"Handske Vinyl L Pf",
"Mössa Nät Non Wowen 100st Imp",
"Kockmössa Båt Eng 100st",
"Torkpapper 110m",
"Kaffefilter Brew 250st",
"Kaffefilter Ob 110mm Bm 250st",
"Maskindisk Pollux 08 10L",
"R-ett Vega Maskindisk 28 4kg",
"Fryspåsar 4L 30st",
"Korgpåsar Vit 30L 100st",
"Bärkassar Vit 15L 500st",
"Bärkassar Vit 20L 500st",
"Påse Papper Brun Nr3",
"Kanister Nr3 Q-line 500st",
"Grillrent 500ml",
"Pant",
"Retur röd back utan glas",
"Retur röd back m.glas 20x33 cl",
"Servett 24x24cm Vit 1L",
"Servett 25x25cm Vit 1-lags 500st",
"Sopsäck Svart 60L 10st",
"Sopsäck 125L Svart 60my 25st",
"Sopsäck Rl Svart 160L 25P",
"Matavfallsäck 100my 125L 10P",
"Sopsäck 240L Svart",
"Assiett 18cm Obeh Vit",
"Tallrik 23cm Vit Obeh",
"Tallrik Djup 18cm Mid 100st",
"Näringsdryck Addera+Apelsin",
"Accent Bordskniv 208mm",
"Accent Bordsgaffel 192mm",
"Accent Kaffesked 137mm",
"Accent Bordssked 195mm",
"Astra Serveringssked 240mm",
"Arthur Bordssked 180mm",
"Värmehäll 530x325x40 Wp 250",
"Värmehäll Gn 1/1 Glask/Alum",
"Serveringsvagn Sv 3 hyllplan",
"Täcksidor Vagn",
"Conique Dricksglas 20cl",
"Springform 30cm Lös botten",
"Vispskål 5.5L Plast",
"Termometer Stek Digital",
"Instickstermometer",
"Bakform 1.5l 250mm Bl.plåt",
"Termometer Digital",
"Bunke 6L Rfr",
"Termometer Laser",
"Skalkniv 100mm Svart",
"Kniv Japansk 170mm",
"Kockkniv 200mm Röd Pp-Htg",
"Kockkniv 200mm Blå Pp-Htg",
"Kockkniv 200mm Grön Pphtg",
"Serveringstång 230mm Rfr",
"Slev 190mm Vit Melamin",
"Smörgåstång L225mm Rfr",
"Flottyrslev D160L555mm Destino",
"Spiralvisp 310mm Rfr",
"Kantin 1/1-65",
"Kaffeburk 2L Måttskopa",
"Kantin 1/2-150",
"Kantin 1/1-65 Perf Htg",
"Kantinlock1/9 Klar",
"Kantin Gastronorm 1/3-65",
"Gastronorm Kantin 1/1-65",
"Kantin 1/1 12 L",
"Kantin 1/2 7.9 L",
"Kastrull 3L D200 H105mm",
"Kantin Gastro 1/2 5.96 L",
"Kastrull 1L D140 H65mm",
"Stekpanna Rfr/nons 24cm",
"Karott 1.1L 200mm Rfr",
"Påsklämma Mega 1st",
"Glas 28cl Poly",
"Lock 200mm T Karott  Rfr 8",
"Progress Tallrik Fl 240mm",
"Progress Tallrik Fl 235mm Granit",
"Progress Plasttallrik Dj 240mm ",
"Progress Tallrik Fl 240mm Granit",
"Progress Tallrik Vit Dj 240mm",
"Plasttallrik Fl1 80mm",
"Tallrik Flat 22.9cm Vit Polyc",
"Banquet Mugg 30cl Stb",
"Banquet Tallrik Fl 250",
"Banquet Tallrik Fl 190",
"Banquet Tallrik Dj 230",
"Banquet Äggkopp",
"Mugg Attila Vit/Röd 20cl",
"Banquet Tallrik Djup 260 ",
"Progress Tallrik Granit Dj 180mm",
"Kaszub Tallrik Fl 240mm Vit",
"Sköljlåda Vit Plast 9L",
"Mugg 24cl Grå Stapelbar",
"Spillback Plast 510x510x40",
"Mugg Attila Röd/Vit 20cl",
"Salladsskål 165mm",
"America Glassked 220mm",
"Bestickkorg Rund",
"Termoskanna Rfr 1L",
"Termoskanna RFfr 1.9L",
"Termoskanna Krom Tryck 1L ",
"Brödkorg Rund 170mm",
"Brödfat Ovalt 300x220 H70",
"Bricka Björk 430x330",
"Termos Serveringsstation 2.5L",
"Tillbringare 1.8L"]